name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - doxygen_support/0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: Docs/doxygen/doxygen_build/html
          config_file: Docs/doxygen/doxygen-local.config